PerfSpike/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using PerfSpike.Areas.HelpPage.ModelDescriptions;

namespace PerfSpike.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

PerfSpike/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using PerfSpike.Areas.HelpPage.ModelDescriptions;
using PerfSpike.Areas.HelpPage.Models;

namespace PerfSpike.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

PerfSpike/Controllers/DocumentFragmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfSpike.Controllers
{
    public class DocumentFragmentController : Controller
    {
        // GET: DocumentFragment
        public ActionResult Index()
        {
            return View();
        }
    }
}

PerfSpike/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfSpike.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

PerfSpike/Controllers/StandardKOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfSpike.Controllers
{
    public class StandardKOController : Controller
    {
        // GET: StandardKO
        public ActionResult Index()
        {
            return View();
        }
    }
}

PerfSpike/Controllers/TemplatesDocFragmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PerfSpike.Controllers
{
    public class TemplatesDocFragmentController : Controller
    {
        // GET: TemplatesDocFragment
        public ActionResult Index()
        {
            return View();
        }
    }
}

PerfSpike/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.Remoting.Messaging;
using System.Web.Http;
using Antlr.Runtime;

namespace PerfSpike.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<dynamic> Get()
        {
            var result = Enumerable.Range(0, 100).Select(x => new {name = "Petter" + x, values = Enumerable.Range(0, 3*24).ToArray()}).ToArray();
            return result;
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

PerfSpike/Views/DocumentFragment/Index.cshtml
<div class="row" id="main-table">

</div>
<script src="~/Scripts/app/docFragmentKO.js"></script>

PerfSpike/Views/Home/Index.cshtml
<div class="jumbotron">
    <p>@Html.ActionLink("Standard Knockout.js", "Index", "StandardKO")</p>
    <p>@Html.ActionLink("DocumentFragment knockout.js", "Index", "DocumentFragment")</p>
    <p>@Html.ActionLink("DocumentFragment knockout.js templates", "Index", "TemplatesDocFragment")</p>
</div>

PerfSpike/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

  
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <script src="~/Scripts/app/dataService.js"></script>
    </body>
</html>

PerfSpike/Views/StandardKO/Index.cshtml
<div class="row" id="main-table">
        <table class="table table-condensed">
            <thead></thead>
            <tbody data-bind="foreach:people">
                <tr>
                    <td data-bind="text:name"></td>
                    <!-- ko foreach: values -->
                    <td data-bind="text:$data"></td>
                    <!--/ko-->
                </tr>
            </tbody>
        </table>
    </div>
<script src="~/Scripts/app/standardKO.js"></script>

PerfSpike/Views/TemplatesDocFragment/Index.cshtml
<div class="row" id="main-table-container">
    <div id="header-container"></div>
    <h1 id="rendering-message">Rendering.... <i class="glyphicon glyphicon-cog"></i></h1>
    <div id="content-container"></div>
</div>

<script type="text/html" id="header">
    <!-- ko foreach: people -->
    <span class="label label-success glyphicon glyphicon-tint" data-bind="text:name"></span>
    <!-- /ko -->
</script>

<script type="text/html" id="main-table">
    <table class="table table-condensed">
        <!-- ko template: {name: 'table-head'}-->
        <!-- /ko -->
        <!-- ko template: {name: 'table-body'}-->
        <!-- /ko -->
    </table>
</script>

<script type="text/html" id="table-head">
    <thead>
        <tr>
            <th></th>
            <!-- ko foreach: people[0].values-->
            <th data-bind="text:$index"></th>
            <!-- /ko -->
        </tr>
    </thead>
</script>

<script type="text/html" id="table-body">
    <tbody data-bind="foreach:people">
        <tr>
            <td data-bind="text:name"></td>
            <!-- ko foreach: values -->
            <td data-bind="text:$data"></td>
            <!--/ko-->
        </tr>
    </tbody>
</script>
<script src="~/Scripts/app/docFragmentTemplateKO.js"></script>